config/routes.rb
Rubysocial::Application.routes.draw do
  post "registro/index"

  get "sitio/index"

  get "sitio/quienes"

  get "sitio/ayuda"

  root :to => 'sitio#index'
  match "/ayuda" => "sitio#ayuda", :as => "ayuda"
  match "/quienes" => "sitio#quienes", :as => "quienes"
  match "/home" => "sitio#index", :as => "home"
  match "/loguin" => "registro#index", :as => "loguin"

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :nombre, :email, :password,
    :message => "Campo en blanco"

  validates_length_of :nombre, :within => 6..10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/registro_controller.rb
class RegistroController < ApplicationController
  def index
    if request.post?
      @user = User.new(params[:user])
      if @user.save
        flash[:notice]= "El usuario #{@user.nombre} se ha guardado correctamente."
        redirect_to home_url
      end
    end
  end
end

app/controllers/sitio_controller.rb
class SitioController < ApplicationController
  def index
    @titulo = "RubySocial"
  end

  def quienes
    @titulo = "Quienes Somos"
  end

  def ayuda
    @titulo = "Ayuda"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registro_helper.rb
module RegistroHelper
end

app/helpers/sitio_helper.rb
module SitioHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=  @titulo %></title>
  <%= stylesheet_link_tag "reset" %>
  <%= stylesheet_link_tag "estilos" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="contenido">
    <div id="cabecera">
      <h1><%= @titulo %></h1>
    </div>
    <div id="menu">
      <%= link_to_unless_current "Inicio", home_url %>
      <%= link_to_unless_current "Quiénes Somos",quienes_url %>
      <%= link_to_unless_current "Ayuda",ayuda_url %>
      <%= link_to_unless_current "Registro",loguin_url %>
    </div>
    <div id="contenido_main">
      <%= yield %>
    </div>
  </div>
  <%=%>


</body>
</html>

app/views/registro/index.html.erb
<%= form_for :user do |f| %>
  <%= error_messages_for "user" %>

<fieldset id="formulario">
  <legend>Registro </legend>
  <ul>
    <li>
      <%= f.label :nombre %>
      <%= f.text_field :nombre %>
    </li>
    <li>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </li>
    <li>
      <%= f.label :password %>
      <%= f.text_field :password %>
    </li>
    <li>
      <%= f.submit "Guardar" %>
    </li>
  </ul>
</fieldset>
<%end%>

app/views/sitio/ayuda.html.erb
<p>Contáctenos</p>

app/views/sitio/index.html.erb
<%=  flash[:notice] %>
<p>Bienvenidos a nuestra Red Social. Karen Ramírez</p>

app/views/sitio/quienes.html.erb
<p>Quiénes Somos</p>